server:
  port: 9091
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/QuanticGameDev/cloud-properties.git
          search-paths:
          - '{application}'
          
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9092/eureka/
  instance:
    hostname: localhost