spring:
  profiles: uat
  application:
    name: auth-server
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/liberty?createDatabaseIfNotExist=true
    username: root
    password: myPassword
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
   
server:
  port: 9098

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9092/eureka/
  instance:
    hostname: localhost
