spring:
  profiles: dev
  application:
    name: auth-server
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/liberty?createDatabaseIfNotExist=true
    username: root
    password: myPassword
   
server:
  port: 9098

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9092/eureka/
  instance:
    hostname: localhost